version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: challenge_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_challenge_node
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    volumes:
      - ./db-data:/var/lib/mysql
